-- Generated by tools/fetch_enchants.py
-- Source: wago.tools SpellItemEnchantment.db2
-- Slot from the trade-name prefix, stat from the db2 effect columns
-- stat = "Special" marks a proc enchant: no secondary stat to match on,
-- so the pick falls back to catalogue order or a per-spec override.

BiSHelper_Enchants = {
    season = "Midnight Season 2",
    slots = {
        [1] = {
            { name = "Empowered Rune of Avoidance", stat = "Avoidance", ranks = {8016, 8017} },
            { name = "Blessing of Speed", stat = "Speed", ranks = {7988, 7989} },
            { name = "Empowered Blessing of Speed", stat = "Speed", ranks = {7990, 7991} },
            { name = "Empowered Hex of Leeching", stat = "Leech", ranks = {7960, 7961} },
            { name = "Hex of Leeching", stat = "Leech", ranks = {7958, 7959} },
            { name = "Rune of Avoidance", stat = "Avoidance", ranks = {8014, 8015} },
        },
        [3] = {
            { name = "Amirdrassil's Grace", stat = "Avoidance", ranks = {8000, 8001} },
            { name = "Akil'zon's Swiftness", stat = "Speed", ranks = {7972, 7973} },
            { name = "Flight of the Eagle", stat = "Speed", ranks = {7970, 7971} },
            { name = "Nature's Grace", stat = "Avoidance", ranks = {7998, 7999} },
            { name = "Silvermoon's Mending", stat = "Leech", ranks = {8030, 8031} },
            { name = "Thalassian Recovery", stat = "Leech", ranks = {8028, 8029} },
        },
        [5] = {
            { name = "Mark of the Worldsoul", stat = "Agility/Strength/Intellect", ranks = {7986, 7987} },
            { name = "Mark of Nalorakk", stat = "Strength", ranks = {7956, 7957} },
            { name = "Mark of the Magister", stat = "Intellect", ranks = {8012, 8013} },
            { name = "Mark of the Rootwarden", stat = "Agility", ranks = {7984, 7985} },
        },
        [8] = {
            { name = "Farstrider's Hunt", stat = "Speed", ranks = {8018, 8019} },
            { name = "Lynx's Dexterity", stat = "Avoidance", ranks = {7962, 7963} },
            { name = "Shaladrassil's Roots", stat = "Leech", ranks = {7992, 7993} },
        },
        [11] = {
            { name = "Amani Mastery", stat = "Mastery", ranks = {7964, 7965} },
            { name = "Eyes of the Eagle", stat = "Special", ranks = {7966, 7967} },
            { name = "Nature's Fury", stat = "Critical Strike", ranks = {7996, 7997} },
            { name = "Nature's Wrath", stat = "Critical Strike", ranks = {7994, 7995} },
            { name = "Silvermoon's Alacrity", stat = "Haste", ranks = {8024, 8025} },
            { name = "Silvermoon's Tenacity", stat = "Versatility", ranks = {8026, 8027} },
            { name = "Thalassian Haste", stat = "Haste", ranks = {8020, 8021} },
            { name = "Thalassian Versatility", stat = "Versatility", ranks = {8022, 8023} },
            { name = "Zul'jin's Mastery", stat = "Mastery", ranks = {7968, 7969} },
        },
        [16] = {
            { name = "Acuity of the Ren'dorei", stat = "Special", ranks = {8038, 8039} },
            { name = "Arcane Mastery", stat = "Special", ranks = {8040, 8041} },
            { name = "Berserker's Rage", stat = "Special", ranks = {7982, 7983} },
            { name = "Flames of the Sin'dorei", stat = "Special", ranks = {8036, 8037} },
            { name = "Jan'alai's Precision", stat = "Special", ranks = {7980, 7981} },
            { name = "Strength of Halazzi", stat = "Special", ranks = {7978, 7979} },
            { name = "Worldsoul Aegis", stat = "Special", ranks = {8008, 8009} },
            { name = "Worldsoul Cradle", stat = "Special", ranks = {8006, 8007} },
            { name = "Worldsoul Tenacity", stat = "Special", ranks = {8010, 8011} },
        },
    },
}
