-- Generated by tools/fetch_gems.py
-- Source: Blizzard Game Data API (item class 3)
-- Single-stat gems only, strongest rank per secondary stat.

BiSHelper_Gems = {
    season = "Midnight Season 2",
    byStat = {
        ["Critical Strike"] = { itemID = 240904, name = "Flawless Deadly Garnet" },  -- +15
        ["Haste"] = { itemID = 240888, name = "Flawless Quick Peridot" },  -- +15
        ["Mastery"] = { itemID = 240896, name = "Flawless Masterful Amethyst" },  -- +15
        ["Versatility"] = { itemID = 240912, name = "Flawless Versatile Lapis" },  -- +15
    },
}
