#!/usr/bin/env python3
"""Generate addon/data/enchants.lua from SpellItemEnchantment.db2.

Blizzard's Game Data API has no enchantment endpoint, so the ranks come from
wago.tools' db2 export. That file carries the trade name and the quality tier
but NOT the slot an enchant applies to — deriving that would mean chaining
ItemSparse -> ItemEffect -> SpellEffect for a catalogue of ~25 entries, which
does not pay for itself. SLOT_MAP below supplies slot and stat by hand.

The split is deliberate: IDs and ranks come from db2 because a mistake there
is silent and expensive; slot and stat come from SLOT_MAP because a mistake
there is visible in game immediately.

Usage:  python tools/fetch_enchants.py
"""
import csv
import json
import os
import re
import sys
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(REPO, "tools", "cache", "SpellItemEnchantment.csv")
OUT = os.path.join(REPO, "addon", "data", "enchants.lua")
SEASON = "Midnight Season 2"

TIER_RE = re.compile(r"^(.*?)\s*\|A:Professions-ChatIcon-Quality-Tier(\d):")

# Slot id and stat per enchant family. Stat names must match
# statPriority[mode].stats[].name in the spec data files verbatim.
# Slot ids follow SLOTS in BiS_Helper.lua; ring 11 also serves ring 12.
SLOT_MAP = {
    "Chant of Winged Grace":   {"slot": 15, "stat": "Avoidance"},
    "Chant of Leeching Fangs": {"slot": 15, "stat": "Leech"},
    # ... uzupełnij z tools/cache/enchants_midnight_s2_notes.md (Task 2)
}


def parse_tier(raw_name):
    """('Chant of Winged Grace |A:...Tier3:...|a') -> ('Chant of Winged Grace', 3)"""
    match = TIER_RE.match(raw_name)
    if not match:
        return None
    return match.group(1).strip(), int(match.group(2))


def group_ranks(rows):
    """[(id, raw_name)] -> {base_name: [rank1_id, rank2_id, rank3_id]}

    Families without all three tiers are dropped: a partial family would let
    the addon call a legitimate max-rank enchant 'low rank'.
    """
    by_name = {}
    for enchant_id, raw_name in rows:
        parsed = parse_tier(raw_name)
        if not parsed:
            continue
        base, tier = parsed
        by_name.setdefault(base, {})[tier] = int(enchant_id)

    return {
        name: [tiers[1], tiers[2], tiers[3]]
        for name, tiers in by_name.items()
        if set(tiers) == {1, 2, 3}
    }


def resolve_slot(name):
    """Slot and stat for an enchant family. Raises KeyError when unknown —
    guessing would put an enchant on the wrong row with no visible error."""
    return SLOT_MAP[name]


def render_lua(catalog, season):
    """{slot_id: [{name, stat, ranks}]} -> contents of enchants.lua"""
    lines = [
        "-- Generated by tools/fetch_enchants.py",
        "-- Source: wago.tools SpellItemEnchantment.db2",
        "-- Slot and stat mapping: SLOT_MAP in the generator (manual)",
        "",
        "BiSHelper_Enchants = {",
        '    season = "%s",' % season,
        "    slots = {",
    ]
    for slot_id in sorted(catalog):
        lines.append("        [%d] = {" % slot_id)
        for entry in sorted(catalog[slot_id], key=lambda e: e["name"]):
            ranks = ", ".join(str(r) for r in entry["ranks"])
            lines.append(
                '            { name = "%s", stat = "%s", ranks = {%s} },'
                % (entry["name"], entry["stat"], ranks)
            )
        lines.append("        },")
    lines += ["    },", "}", ""]
    return "\n".join(lines)


def load_rows(path):
    with open(path, encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        return [(row["ID"], row["Name_lang"]) for row in reader]


def main():
    if not os.path.exists(CACHE):
        print("Brak %s — pobierz go najpierw (Task 2, krok 1)." % CACHE)
        return 2

    ranks_by_name = group_ranks(load_rows(CACHE))

    catalog, unknown = {}, []
    for name, ranks in ranks_by_name.items():
        if name not in SLOT_MAP:
            unknown.append(name)
            continue
        info = SLOT_MAP[name]
        catalog.setdefault(info["slot"], []).append(
            {"name": name, "stat": info["stat"], "ranks": ranks}
        )

    if not catalog:
        print("SLOT_MAP nie pokrywa zadnej rodziny z db2 — sprawdz Task 2.")
        return 1

    # CRLF: .lua files in this repo use CRLF; newline="" preserves what we write.
    with open(OUT, "w", encoding="utf-8", newline="") as fh:
        fh.write(render_lua(catalog, SEASON).replace("\n", "\r\n"))

    total = sum(len(v) for v in catalog.values())
    print("Zapisano %s — %d enchantow w %d slotach" % (OUT, total, len(catalog)))
    if unknown:
        print("\nRodziny w db2 bez wpisu w SLOT_MAP (%d):" % len(unknown))
        for name in sorted(unknown):
            print("   %s" % name)
        print("Dopisz te, ktore naleza do Midnight S2, reszte zignoruj.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
