#!/usr/bin/env python3
"""Generate addon/data/gems.lua from the Blizzard Game Data API.

Unlike enchants, gems are ordinary items, so the API has everything: the id the
addon needs to compare against a socketed gem, the name, and the stat. Two
fields carry the stat and they agree, so the effect string is parsed and the
subclass is left alone.

Only single-stat gems reach the catalogue. Hybrids ("+11 Critical Strike & +4
Haste") would need a weighting rule the addon has no basis for, and the
prismatic Eversong Diamonds grant Primary Stat, which never appears in a spec's
stat priority. Both are visible in the run summary but not emitted.

Usage:  python tools/fetch_gems.py [--min-id N] [--dry-run]
"""
import argparse
import os
import re
import sys
import urllib.parse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import blizzard_api

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "addon", "data", "gems.lua")
SEASON = "Midnight Season 2"

GEM_ITEM_CLASS = 3

# Midnight's gems start here. Older expansions' gems are still in the API and
# would otherwise win on nothing but appearing first.
DEFAULT_MIN_ID = 240000

# "+15 Haste" but not "+11 Critical Strike & +4 Haste": the ampersand form is
# a hybrid and is deliberately excluded.
PURE_EFFECT_RE = re.compile(r"^\+(\d+)\s+([A-Za-z][A-Za-z ]*?)\s*$")

# Stats that can appear in statPriority[mode].stats[].name. A gem for anything
# else can never be matched to a spec, so emitting it would be dead weight.
SECONDARY_STATS = {"Critical Strike", "Haste", "Mastery", "Versatility"}


def parse_effect(effect):
    """'+15 Haste' -> (15, 'Haste'); None for hybrids and proc text."""
    if not effect:
        return None
    match = PURE_EFFECT_RE.match(effect.strip())
    if not match:
        return None
    return int(match.group(1)), match.group(2).strip()


def pick_best(gems):
    """[{id, name, stat, amount}] -> {stat: gem} keeping the strongest per stat.

    Ties break on the lower id so a rerun cannot silently swap the choice.
    """
    best = {}
    for gem in gems:
        current = best.get(gem["stat"])
        if not current or (gem["amount"], -gem["id"]) > (current["amount"], -current["id"]):
            best[gem["stat"]] = gem
    return best


def _reject_markup(value, field):
    """`|` opens an escape sequence in WoW's UI markup and `"` would break the
    Lua string literal. Neither can be escaped away safely, so refuse to emit."""
    if "|" in value or '"' in value:
        raise ValueError(
            "niedozwolony znak w polu %s: %r (| psuje markup UI, \" psuje skladnie Lua)"
            % (field, value)
        )


def render_lua(best, season):
    """{stat: gem} -> contents of gems.lua"""
    lines = [
        "-- Generated by tools/fetch_gems.py",
        "-- Source: Blizzard Game Data API (item class 3)",
        "-- Single-stat gems only, strongest rank per secondary stat.",
        "",
        "BiSHelper_Gems = {",
        '    season = "%s",' % season,
        "    byStat = {",
    ]
    for stat in sorted(best):
        gem = best[stat]
        _reject_markup(stat, "stat")
        _reject_markup(gem["name"], "name")
        lines.append(
            '        ["%s"] = { itemID = %d, name = "%s" },  -- +%d'
            % (stat, gem["id"], gem["name"], gem["amount"])
        )
    lines += ["    },", "}", ""]
    return "\n".join(lines)


def fetch_gems(min_id):
    """Every gem item at or above min_id, with its effect string."""
    env = blizzard_api.load_env()
    region = env.get("BLIZZARD_REGION", "eu")
    locale = env.get("BLIZZARD_LOCALE", "en_US")
    token = blizzard_api.get_access_token(
        env["BLIZZARD_CLIENT_ID"], env["BLIZZARD_CLIENT_SECRET"], region)

    def api(path, **params):
        params.setdefault("namespace", "static-%s" % region)
        params.setdefault("locale", locale)
        return blizzard_api.api_get(
            "https://%s.api.blizzard.com%s?%s"
            % (region, path, urllib.parse.urlencode(params)), token)

    ids = []
    for page in range(1, 12):
        data = api("/data/wow/search/item", **{
            "item_class.id": GEM_ITEM_CLASS, "orderby": "id:desc",
            "_page": page, "_pageSize": 100})
        results = data.get("results", [])
        if not results:
            break
        below = False
        for hit in results:
            item_id = hit["data"]["id"]
            if item_id >= min_id:
                ids.append(item_id)
            else:
                below = True
        # Sorted descending, so the first id under the floor ends the walk.
        if below or (data.get("pageCount") and page >= data["pageCount"]):
            break

    gems = []
    for item_id in sorted(ids):
        detail = api("/data/wow/item/%d" % item_id)
        props = (detail.get("preview_item", {}) or {}).get("gem_properties") or {}
        gems.append({
            "id": item_id,
            "name": detail.get("name") or "",
            "effect": props.get("effect"),
        })
    return gems


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--min-id", type=int, default=DEFAULT_MIN_ID,
                        help="lowest item id to consider (default: %d)" % DEFAULT_MIN_ID)
    parser.add_argument("--dry-run", action="store_true",
                        help="print what would be written, write nothing")
    args = parser.parse_args()

    raw = fetch_gems(args.min_id)
    print("Gemow z API (id >= %d): %d" % (args.min_id, len(raw)))

    pure, skipped = [], []
    for gem in raw:
        parsed = parse_effect(gem["effect"])
        if not parsed:
            skipped.append(gem)
            continue
        amount, stat = parsed
        if stat not in SECONDARY_STATS:
            skipped.append(gem)
            continue
        pure.append({"id": gem["id"], "name": gem["name"], "stat": stat, "amount": amount})

    if not pure:
        print("Zaden gem nie ma czystego statu wtornego - sprawdz --min-id.")
        return 1

    best = pick_best(pure)
    missing = sorted(SECONDARY_STATS - set(best))
    if missing:
        print("UWAGA: brak gemu dla statu: %s" % ", ".join(missing))

    for stat in sorted(best):
        gem = best[stat]
        print("   %-16s %7d  %-32s +%d" % (stat, gem["id"], gem["name"], gem["amount"]))

    if args.dry_run:
        print("\n--dry-run: nic nie zapisano")
        return 0

    # CRLF: .lua files in this repo use CRLF; newline="" preserves what we write.
    with open(OUT, "w", encoding="utf-8", newline="") as fh:
        fh.write(render_lua(best, SEASON).replace("\n", "\r\n"))
    print("\nZapisano %s - %d statow (pominieto %d hybryd i efektow)"
          % (OUT, len(best), len(skipped)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
