"""
Generate addon/data/mplus_loot.lua from tools/mplus_loot_midnight_s1.json.
"""

import json
import os
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
JSON_PATH = os.path.join(SCRIPT_DIR, "mplus_loot_midnight_s1.json")
LUA_PATH = os.path.join(SCRIPT_DIR, "..", "addon", "data", "mplus_loot.lua")

SLOT_NORMALIZE = {
    "Main Hand": "Weapon",
    "Off Hand": "Weapon",
    "One-Hand": "Weapon",
    "Two-Hand": "Weapon",
    "Ranged": "Weapon",
    "Held In Off-hand": "Weapon",
}


def lua_str(s):
    if s is None:
        return "nil"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'") + '"'


def format_stats(stats_dict):
    if not stats_dict:
        return None
    return " / ".join(sorted(stats_dict.keys()))


def main():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    items = data["items"]
    season = data.get("season", "Unknown")

    lines = []
    lines.append(f"-- Generated by tools/generate_loot_lua.py")
    lines.append(f"-- Source: {data.get('source', 'unknown')}")
    lines.append(f"-- Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"-- Items: {len(items)}")
    lines.append("")
    lines.append("BiSHelper_MplusLoot = {")
    lines.append(f'    season = {lua_str(season)},')
    lines.append(f"    items = {{")

    for item in items:
        item_id = item["itemID"]
        name = item.get("name", "Unknown")
        slot_raw = item.get("slot")
        slot = SLOT_NORMALIZE.get(slot_raw, slot_raw)
        armor_type = item.get("armorType")
        weapon_type = item.get("weaponType")
        stats = format_stats(item.get("stats"))
        dungeon = item.get("dungeon")
        boss = item.get("droppedBy")

        parts = [
            f"itemID={item_id}",
            f"name={lua_str(name)}",
            f"slot={lua_str(slot)}",
            f"armorType={lua_str(armor_type)}",
            f"weaponType={lua_str(weapon_type)}",
            f"stats={lua_str(stats)}",
            f"dungeon={lua_str(dungeon)}",
            f"boss={lua_str(boss)}",
        ]
        lines.append(f"        {{ {', '.join(parts)} }},")

    lines.append("    },")
    lines.append("}")
    lines.append("")

    with open(LUA_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {LUA_PATH} with {len(items)} items.")


if __name__ == "__main__":
    main()
