"""
Generate addon/data/mplus_loot.lua from a JSON loot file.
Usage: python generate_loot_lua.py [--input path/to/loot.json]
"""

import argparse
import json
import os
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_LUA_PATH = os.path.join(SCRIPT_DIR, "..", "addon", "data", "mplus_loot.lua")

SLOT_NORMALIZE = {
    "Main Hand": "Weapon",
    "Off Hand": "Weapon",
    "One-Hand": "Weapon",
    "Two-Hand": "Weapon",
    "Ranged": "Weapon",
    "Held In Off-hand": "Weapon",
}


def lua_str(s):
    if s is None:
        return "nil"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'") + '"'


def find_latest_json():
    """Find the most recently modified mplus_loot_*.json in the script directory."""
    candidates = []
    for f in os.listdir(SCRIPT_DIR):
        if f.startswith("mplus_loot_") and f.endswith(".json"):
            path = os.path.join(SCRIPT_DIR, f)
            candidates.append((os.path.getmtime(path), path))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]


def main():
    parser = argparse.ArgumentParser(description="Generate mplus_loot.lua from JSON")
    parser.add_argument("--input", type=str, default=None, help="Path to JSON loot file")
    parser.add_argument("--output", type=str, default=DEFAULT_LUA_PATH, help="Output Lua path")
    parser.add_argument("--min-ilvl", type=int, default=100, help="Min ilvl for current-season flag (default: 100)")
    parser.add_argument("--whitelist", type=str, default=None,
                        help="Path to whitelist JSON (from parse_loot_export.py). Overrides --min-ilvl for current flag.")
    args = parser.parse_args()

    json_path = args.input or find_latest_json()
    if not json_path or not os.path.exists(json_path):
        print("ERROR: No JSON loot file found. Run fetch_blizzard_loot.py first.")
        return

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    items = data["items"]

    # Load whitelist if provided
    whitelist_ids = None
    if args.whitelist:
        if not os.path.exists(args.whitelist):
            print(f"ERROR: Whitelist file not found: {args.whitelist}")
            return
        with open(args.whitelist, "r", encoding="utf-8") as wf:
            wl_data = json.load(wf)
        whitelist_ids = set(wl_data.get("itemIDs", []))
        print(f"Using whitelist: {len(whitelist_ids)} item IDs from {args.whitelist}")

    season = data.get("season", "Unknown")
    source = data.get("source", "Unknown")

    lines = []
    lines.append(f"-- Generated by tools/generate_loot_lua.py")
    lines.append(f"-- Source: {source}")
    lines.append(f"-- Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"-- Items: {len(items)}")
    lines.append("")
    lines.append("BiSHelper_MplusLoot = {")
    lines.append(f'    season = {lua_str(season)},')
    lines.append(f"    items = {{")

    for item in items:
        item_id = item["itemID"]
        name = item.get("name", "Unknown")
        slot_raw = item.get("slot")
        slot = SLOT_NORMALIZE.get(slot_raw, slot_raw)
        ilvl = item.get("ilvl", 0)
        if whitelist_ids is not None:
            current = item_id in whitelist_ids
        else:
            current = ilvl >= args.min_ilvl
        armor_type = item.get("armorType")
        weapon_type = item.get("weaponType")
        stats = item.get("stats")
        dungeon = item.get("dungeon")
        boss = item.get("boss")

        parts = [
            f"itemID={item_id}",
            f"name={lua_str(name)}",
            f"slot={lua_str(slot)}",
            f"ilvl={ilvl}",
            f"armorType={lua_str(armor_type)}",
            f"weaponType={lua_str(weapon_type)}",
            f"stats={lua_str(stats)}",
            f"dungeon={lua_str(dungeon)}",
            f"boss={lua_str(boss)}",
            f"current={'true' if current else 'false'}",
            'sourceType="mythicplus"',
        ]
        lines.append(f"        {{ {', '.join(parts)} }},")

    lines.append("    },")
    lines.append("}")
    lines.append("")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {args.output} with {len(items)} items.")


if __name__ == "__main__":
    main()
