"""
Generate addon/data/raid_loot.lua from a JSON raid loot file.
Usage: python generate_raid_loot_lua.py [--input path/to/raid_loot.json]
"""

import argparse
import json
import os
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_LUA_PATH = os.path.join(SCRIPT_DIR, "..", "addon", "data", "raid_loot.lua")

SLOT_NORMALIZE = {
    "Main Hand": "Weapon",
    "Off Hand": "Weapon",
    "One-Hand": "Weapon",
    "Two-Hand": "Weapon",
    "Ranged": "Weapon",
    "Held In Off-hand": "Weapon",
}


def lua_str(s):
    if s is None:
        return "nil"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'") + '"'


def find_latest_json():
    """Find the most recently modified raid_loot_*.json in the script directory."""
    candidates = []
    for f in os.listdir(SCRIPT_DIR):
        if f.startswith("raid_loot_") and f.endswith(".json"):
            path = os.path.join(SCRIPT_DIR, f)
            candidates.append((os.path.getmtime(path), path))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]


def main():
    parser = argparse.ArgumentParser(description="Generate raid_loot.lua from JSON")
    parser.add_argument("--input", type=str, default=None, help="Path to JSON raid loot file")
    parser.add_argument("--output", type=str, default=DEFAULT_LUA_PATH, help="Output Lua path")
    args = parser.parse_args()

    json_path = args.input or find_latest_json()
    if not json_path or not os.path.exists(json_path):
        print("ERROR: No JSON raid loot file found. Run fetch_raid_loot.py first.")
        return

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    items = data["items"]
    season = data.get("season", "Unknown")
    source = data.get("source", "Unknown")

    lines = []
    lines.append("-- Generated by tools/generate_raid_loot_lua.py")
    lines.append(f"-- Source: {source}")
    lines.append(f"-- Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"-- Items: {len(items)}")
    lines.append("")
    lines.append("BiSHelper_RaidLoot = {")
    lines.append(f'    season = {lua_str(season)},')
    lines.append("    items = {")

    for item in items:
        item_id = item["itemID"]
        name = item.get("name", "Unknown")
        slot_raw = item.get("slot")
        slot = SLOT_NORMALIZE.get(slot_raw, slot_raw)
        ilvl = item.get("ilvl", 0)
        armor_type = item.get("armorType")
        weapon_type = item.get("weaponType")
        stats = item.get("stats")
        dungeon = item.get("dungeon")
        boss = item.get("boss")

        parts = [
            f"itemID={item_id}",
            f"name={lua_str(name)}",
            f"slot={lua_str(slot)}",
            f"ilvl={ilvl}",
            f"armorType={lua_str(armor_type)}",
            f"weaponType={lua_str(weapon_type)}",
            f"stats={lua_str(stats)}",
            f"dungeon={lua_str(dungeon)}",
            f"boss={lua_str(boss)}",
            "current=true",
            'sourceType="raid"',
        ]
        lines.append(f"        {{ {', '.join(parts)} }},")

    lines.append("    },")
    lines.append("}")
    lines.append("")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {args.output} with {len(items)} items.")


if __name__ == "__main__":
    main()
